In [1]:
# Dependencies and Setup
%matplotlib inline
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

# Hide warning messages in notebook
import warnings
warnings.filterwarnings('ignore')

In [2]:
# File to Load (Remember to Change These)
mouse_drug_data_to_load = "data/mouse_drug_data.csv"
clinical_trial_data_to_load = "data/clinicaltrial_data.csv"

In [3]:
# Read the Mouse and Drug Data and the Clinical Trial Data
mouse_drug_data_to_load = pd.read_csv("data/mouse_drug_data.csv")

In [4]:
clinical_trial_data_to_load =pd.read_csv("data/clinicaltrial_data.csv")

In [19]:
# Combine the data into a single dataset

combined_data_df = pd.merge(clinical_trial_data_to_load, mouse_drug_data_to_load,  on="Mouse ID", how= "outer")
single_data_df = combined_data_df.loc[(combined_data_df["Tumor Volume (mm3)"]== 45.000000)]
single_data_df.head()

   Mouse ID  Timepoint  Tumor Volume (mm3)  Metastatic Sites       Drug
0      b128          0                45.0                 0  Capomulin
10     f932          0                45.0                 0   Ketapril
11     g107          0                45.0                 0   Ketapril
19     a457          0                45.0                 0   Ketapril
22     c819          0                45.0                 0   Ketapril

In [28]:
# Store the Mean Tumor Volume Data Grouped by Drug and Timepoint 
stored = combined_data_df.groupby (['Drug', 'Timepoint']).mean()['Tumor Volume (mm3)']
stored.head()
# Convert to DataFrame
stored_df = pd.DataFrame (stored)
# Preview DataFrame
stored_df

                     Tumor Volume (mm3)
Drug      Timepoint
Capomulin 0                   45.000000
          5                   44.266086
          10                  43.084291
          15                  42.064317
          20                  40.716325
          25                  39.939528
          30                  38.769339
          35                  37.816839
          40                  36.958001
          45                  36.236114
Ceftamin  0                   45.000000
          5                   46.503051
          10                  48.285125
          15                  50.094055
          20                  52.157049
          25                  54.287674
          30                  56.769517
          35                  58.827548
          40                  61.467895
          45                  64.132421
Infubinol 0                   45.000000
          5                   47.062001
          10                  49.403909
          15                  51.296397
          20                  53.197691
          25                  55.715252
          30                  58.299397
          35                  60.742461
          40                  63.162824
          45                  65.755562
...                                 ...
Ramicane  0                   45.000000
          5                   43.944859
          10                  42.531957
          15                  41.495061
          20                  40.238325
          25                  38.974300
          30                  38.703137
          35                  37.451996
          40                  36.574081
          45                  34.955595
Stelasyn  0                   45.000000
          5                   47.527452
          10                  49.463844
          15                  51.529409
          20                  54.067395
          25                  56.166123
          30                  59.826738
          35                  62.440699
          40                  65.356386
          45                  68.438310
Zoniferol 0                   45.000000
          5                   46.851818
          10                  48.689881
          15                  50.779059
          20                  53.170334
          25                  55.432935
          30                  57.713531
          35                  60.089372
          40                  62.916692
          45                  65.960888

[100 rows x 1 columns]

In [ ]:
# Store the Standard Error of Tumor Volumes Grouped by Drug and Timepoint

# Convert to DataFrame

# Preview DataFrame

50.468119963715004